name: path-pulse-iot-backend

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract Go Version
        id: go-version
        run: |
          GO_VERSION=$(grep '^go ' go.mod | awk '{ print $2}')
          echo "Extracted Go version: $GO_VERSION"
          echo "::set-output name=version::$GO_VERSION"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.go-version.outputs.version }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
